[2024-08-28T17:38:54.487+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-08-28T17:38:54.496+0000] {taskinstance.py:2603} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_reddit_pipeline.s3_upload manual__2024-08-28T17:38:51.068280+00:00 [queued]>
[2024-08-28T17:38:54.499+0000] {taskinstance.py:2603} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_reddit_pipeline.s3_upload manual__2024-08-28T17:38:51.068280+00:00 [queued]>
[2024-08-28T17:38:54.500+0000] {taskinstance.py:2856} INFO - Starting attempt 1 of 1
[2024-08-28T17:38:54.505+0000] {taskinstance.py:2879} INFO - Executing <Task(PythonOperator): s3_upload> on 2024-08-28 17:38:51.068280+00:00
[2024-08-28T17:38:54.510+0000] {standard_task_runner.py:72} INFO - Started process 52 to run task
[2024-08-28T17:38:54.513+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'etl_reddit_pipeline', 's3_upload', 'manual__2024-08-28T17:38:51.068280+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/reddit_dag.py', '--cfg-path', '/tmp/tmpj31e2e6z']
[2024-08-28T17:38:54.514+0000] {standard_task_runner.py:105} INFO - Job 3: Subtask s3_upload
[2024-08-28T17:38:54.541+0000] {task_command.py:467} INFO - Running <TaskInstance: etl_reddit_pipeline.s3_upload manual__2024-08-28T17:38:51.068280+00:00 [running]> on host d781d2815eaf
[2024-08-28T17:38:54.576+0000] {taskinstance.py:3122} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Qiqi Xie' AIRFLOW_CTX_DAG_ID='etl_reddit_pipeline' AIRFLOW_CTX_TASK_ID='s3_upload' AIRFLOW_CTX_EXECUTION_DATE='2024-08-28T17:38:51.068280+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-08-28T17:38:51.068280+00:00'
[2024-08-28T17:38:54.577+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-08-28T17:38:55.153+0000] {logging_mixin.py:190} INFO - Bucket already exists
[2024-08-28T17:38:55.157+0000] {taskinstance.py:3301} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/opt/airflow/pipelines/aws_s3_pipeline.py", line 10, in upload_s3_pipeline
    upload_to_s3(s3, file_path, bucket, file_path.split('/')[-1])
  File "/opt/airflow/etls/aws_etl.py", line 24, in upload_to_s3
    s3.put(file_path, bucket='/raw/' + s3_file_name)
  File "/home/airflow/.local/lib/python3.9/site-packages/fsspec/asyn.py", line 118, in wrapper
    return sync(self.loop, func, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/fsspec/asyn.py", line 85, in sync
    coro = func(*args, **kwargs)
TypeError: _put() missing 1 required positional argument: 'rpath'
[2024-08-28T17:38:55.185+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=etl_reddit_pipeline, task_id=s3_upload, run_id=manual__2024-08-28T17:38:51.068280+00:00, execution_date=20240828T173851, start_date=20240828T173854, end_date=20240828T173855
[2024-08-28T17:38:55.200+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-08-28T17:38:55.201+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 3 for task s3_upload (_put() missing 1 required positional argument: 'rpath'; 52)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 2995, in _run_raw_task
    return _run_raw_task(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 3149, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 3173, in _execute_task
    return _execute_task(self, context, task_orig)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/opt/airflow/pipelines/aws_s3_pipeline.py", line 10, in upload_s3_pipeline
    upload_to_s3(s3, file_path, bucket, file_path.split('/')[-1])
  File "/opt/airflow/etls/aws_etl.py", line 24, in upload_to_s3
    s3.put(file_path, bucket='/raw/' + s3_file_name)
  File "/home/airflow/.local/lib/python3.9/site-packages/fsspec/asyn.py", line 118, in wrapper
    return sync(self.loop, func, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/fsspec/asyn.py", line 85, in sync
    coro = func(*args, **kwargs)
TypeError: _put() missing 1 required positional argument: 'rpath'
[2024-08-28T17:38:55.222+0000] {local_task_job_runner.py:261} INFO - Task exited with return code 1
[2024-08-28T17:38:55.240+0000] {taskinstance.py:3891} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-08-28T17:38:55.242+0000] {local_task_job_runner.py:240} INFO - ::endgroup::
